//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monera.Crawler.Boliga
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoligaProperty
    {
        public long Id { get; set; }
        public System.Guid SogeresultaterGuid { get; set; }
        public string Link { get; set; }
        public string Titel { get; set; }
        public string Postnr { get; set; }
        public string PostnrTitel { get; set; }
        public Nullable<decimal> Kontantpris { get; set; }
        public Nullable<decimal> Ejerudgift { get; set; }
        public Nullable<decimal> Kvmpris { get; set; }
        public string Type { get; set; }
        public Nullable<int> Bolig { get; set; }
        public Nullable<int> Grund { get; set; }
        public Nullable<int> Vaerelser { get; set; }
        public string Etage { get; set; }
        public Nullable<int> Byggear { get; set; }
        public Nullable<System.DateTime> Oprettet { get; set; }
        public Nullable<int> Liggetid { get; set; }
        public string BrokerLink { get; set; }
        public string ButikTitel { get; set; }
        public string ButikAdresse { get; set; }
        public string ButikPostnr { get; set; }
        public string ButikPostnrTitel { get; set; }
        public Nullable<int> PrisforskelProcentdel { get; set; }
        public Nullable<decimal> KvmprisBoligen { get; set; }
        public Nullable<decimal> KvmprisOmradet { get; set; }
    }
}
